pipeline {
    agent any // Specifies that the pipeline can run on any available agent (Jenkins node)

    tools { // Defines tools required for the pipeline
        maven 'mvn' // Specifies the Maven tool named 'mvn'
    }

    triggers { // Defines triggers for the pipeline
        cron('H H(8-15)/2 * * 1-5') // Cron trigger to run the pipeline every 2 hours between 8 AM and 3 PM, Monday through Friday
    }

    stages { // Defines stages of the pipeline
        stage('Code Build') { // First stage: Code Build
            steps { // Steps to be executed in this stage
                bat 'mvn clean' // Executes Maven clean command to clean the project
            }
        }

        stage('Unit Test') { // Second stage: Unit Test
            steps { // Steps to be executed in this stage
                script { // Allows scripting within the pipeline
                    try { // Wraps the following steps in a try-catch block to handle exceptions
                        bat 'mvn test' // Executes Maven test command to run unit tests
                    } catch (e) { // Catches any exceptions
                        unstable(' Testing failed! ') // Sets the build status to unstable if tests fail
                        echo "Tests got failed" // Outputs a message indicating test failure
                    }
                }
            }
        }

        stage('Cleanup') { // Third stage: Cleanup
            steps { // Steps to be executed in this stage
                // Add cleanup steps here
                bat 'del /s /q target' // Example: Deletes the 'target' directory generated by Maven build
            }
        }
    }
}
